<!------ PAGE TABLE COINS PRICES ------>

<section class='coins container'>
    
    <h1 class='title'><?= htmlentities($title); ?></h1>
    
    <form id='search-form' method="POST">
        <input class='search-symbol' type="text" name="symbol" value="<?=htmlentities($symbol, ENT_QUOTES, 'UTF-8')?>" placeholder="Search by symbol..."/>
        <button class='submit' type="submit" value="submit"><img src="Assets/Img/search.svg"></img></button>
    </form>
    <p class="alert"><?=htmlentities($message);?></p>
    <div class='table-wrapper'>
        <table class="coins-table">
            <thead>
                <tr>
                    <th id='rank'>Rank</th>
                    <th id='symbol'>Symbol</th>
                    <th class='coin-name'>Name</th>
                    <th>Price</th>
                    <th>24h change (%)</th>
                    <th class='market-cap'>Market Cap</th>
                </tr>
            </thead>
            <tbody>
                <!--display datas from table coins from db-->
                <?php foreach($all_coin as $coin): ?>
                <tr>
                    <td id='rank'><?=htmlentities($coin -> id)?></td>
                    <td id='symbol'><?=htmlentities($coin -> symbol)?></td>
                    <td class='coin-name'><?=htmlentities($coin -> name)?></td>
                    <td><?=htmlentities($coin -> price)?></td>
                    <td><?=htmlentities($coin -> change)?></td>
                    <td class='market-cap'><?=htmlentities($coin -> marketcap)?></td>
                </tr>
            <?php endforeach; ?> 
            </tbody>
        </table>
     </div>      
</section>