<!------ HOME PAGE ------>

<section class="homepage" id='homepage'>
    <div class="homepage-container">
      
        <!--auto typing design -->
        <p class='text'>Prices of top 50 <span class="typed-text"></span><span class="stick">&nbsp;</span></p>
        
        <!--carousel background images-->
        <div class="slide-wrapper">
          <div class="slide">
            <img src="Assets/Img/bg-1.png" alt="crypto background image with astronaut" />
          </div>
        
          <div class="slide">
            <img src="Assets/Img/bg-2.jpeg" alt="" />
          </div>
        
          <div class="slide">
            <img src="Assets/Img/bg-3.png" alt="" />
          </div>
    
          <div class="slide">
            <img src="Assets/Img/bg-4.png" alt="" />
          </div>
        
          <button class="arrow arrow-next"></button>
          <button class="arrow arrow-prev"></button>
        </div>  
    </div>
</section>