<!doctype html>
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Coin Ranking</title>
    <link rel="stylesheet" href="Assets/CSS/style.css" type="text/css" />
    <link rel="icon" href="../Public/Assets/Img/favicon.ico">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
</head>

<body>
    <header id='header'>
        <nav class='nav-container'>
            <a class='logo' href="index.php?url=homePage"><img src=../Public/Assets/Img/logo.png></img></a>
            
            <div class='main-nav'>
                <a href="index.php?url=coin">Prices</a>
                <a href="https://www.coinbase.com/learn">Learn</a>
            </div>
        
            <div class='login-nav'>
                <?php if(isset($_SESSION['email'])){
                ?>
                    <?php if( $_SESSION['role'] == "1") { ?>
                    <a href="index.php?url=user-index">User Manager</a>
                    <?php } ?>
                    <a href="index.php?url=user-update&id=<?php echo htmlentities($_SESSION['id']); ?>"> <?php echo htmlentities($_SESSION['user_name'], ENT_QUOTES, "UTF-8"); ?> </a>            
                    <a href="index.php?url=logout"> Logout </a>
                    

                 
                <?php 
                }
                else {
                    ?>
                    <a class='signup' href="index.php?url=login&block=create"> Sign up </a>
                    <a href="index.php?url=login"> Sign in </a>
                <?php 
                }
                ?>
            </div>
        </nav>
    </header>
    
    <?= $content ?>
    
    <footer id='footer'>
        <div class='footer-container'>
        <nav class="footer-nav">
            <a href="https://www.facebook.com/CoinMarketCap/" target="blank"><i class="fab fa-2x fa-facebook-square"></i></a>
            <a href="https://www.youtube.com/channel/UCnhdZlwVd6ocXGhdSyV9Axg" target="blank"><i class="fab fa-2x fa-youtube"></i></a>
            <a href="https://twitter.com/CoinMarketCap?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor" target="blank"><i class="fab fa-2x fa-twitter-square"></i></a>
        </nav>
        </div>
    </footer>
    
    
    <script type="text/javascript" src="../Public/Assets/JS/auto_type.js"></script>
    <script type="text/javascript" src="../Public/Assets/JS/carousel.js"></script>
    <script type="text/javascript" src="../Public/Assets/JS/404.js"></script>

</body>

</html>