<!--PAGE ERROR 404-->

<section class='page-404'>
    <div class='container-404'>
        <img class='img-404' src="Assets/Img/404.svg"></img>
        <p class='text-404'>This page does not exist</p>
        <div class="btn-404">
            <button id='goback' class="btn">Go Back</button>
            <button class='btn'><a href="index.php?url=homePage">Home Page</a></button>
        </div>
    </div>
</section>
    
